#!/bin/bash

function tab() {
  osascript \
    -e "tell application \"Terminal\"" \
    -e "tell application \"System Events\" to keystroke \"t\" using {command down}" \
    -e "do script \"$1\" in front window" \
    -e "end tell" > /dev/null
}

case "$1" in
      setup:functional:tests)
            tab 'cd frontend && gulp'
            tab 'webdriver-manager start'
            sleep 20
            echo "Please wait..."
            protractor ./frontend/test/conf.js
            ;;
      functional:tests)
            protractor ./frontend/test/conf.js
            ;;
      unit:tests)
            cd frontend
            npm test
            ;;
      eslint)
            eslint app/
            ;;
      backend:tests)
            cd backend
            python3 test.py -b
            ;;
      backend)
            cd backend
            python3 api.py
            ;;
      frontend)
            cd frontend
            gulp
            ;;
      download)
            cd backend
            python3 download_tweets.py
            ;;
      train)
            cd backend
            python3 train_classifier.py
            ;;
      classify)
            cd backend
            python3 -c "from handler.classifiers.sentiment import find_sentiment; find_sentiment()"
            ;;
      convertFile)
            cd backend/handler/classifiers
            python3 convert_training_data.py
            ;;
      *)
            tab 'cd frontend && gulp'
            cd backend
            python3 api.py
esac
